---
- name: Install nodejs
  become: yes
  hosts: all

  tasks:

    - name: Install curl and build-essential
      apt:
        name:
          - curl
          - build-essential
        state: present
        update_cache: yes

    - name: Add NodeSource Node.js 20.x repo
      shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      args:
        executable: /bin/bash

    - name: Install latest Node.js
      apt:
        name: nodejs
        state: latest
        update_cache: yes

    - name: Check Node.js version
      command: node -v
      register: node_version

    - debug:
        msg: "Installed Node.js version is {{ node_version.stdout }}"

