---
- name: Install nodejs
  become: yes
  hosts: all

  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Copy SQL file
      copy:
        src: dumpexpo1.sql
        dest: /tmp/dumpexpo1.sql
        

    - name: Import SQL file into database
      mysql_db:
        name: expo
        state: import  #dump
        target: /tmp/dumpexpo1.sql
        login_user: root
        login_password: "{{root_password}}"
      notify:
        - Restart mysql


  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted