---
- name: test index.php
  become: yes
  hosts: all

  vars_files:
    - vars.yml
  tasks:
    -  name: Update apt cache
       apt:
        update_cache: yes
    -  name: Copy index.php
       copy:
        src: files/index.php
        dest: /var/www/html/index.php
    -  name: Copy config nginx
       copy:
        src: files/default2.conf
        dest: /etc/nginx/sites-available/default
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded         